services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 997:100
    network_mode: 'host'
    volumes:
      - ~/docker_containers/jellyfin/config:/config
      - ~/docker_containers/jellyfin/cache:/cache
      - ~/Torrents:/media:ro
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
  torrent:
    image: markusmcnugen/qbittorrentvpn
    container_name: qbittorrentvpn
    privileged: true
    environment:
      - TZ=America/Los_Angeles
      - PUID=998
      - PGID=100
      - WEBUI_PORT_ENV=8080
      - INCOMING_PORT_ENV=8999
      - VPN_ENABLED=yes
      - LAN_NETWORK=10.0.0.0/24
      - NAME_SERVERS=8.8.8.8,8.8.4.4
    volumes:
      - ~/docker_containers/qbittorent/config:/config
      - ~/Torrents:/downloads
    ports:
      - 8080:8080
      - 8999:8999
      - 8999:8999/udp
    restart: unless-stopped
