services:
  nginxproxymanager:
    image: 'jc21/nginx-proxy-manager:latest' 
    container_name: nginxproxymanager
    restart: unless-stopped 
    ports:
      - '80:80'
      - '81:81'
      - '443:443' 
    volumes:
      - /home/nicholas/docker_containers/nginx/data:/data
      - /home/nicholas/docker_containers/nginx/letsencrypt:/etc/letsencrypt 
  
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 997:100
    environment:
      - TZ=America/Los_Angeles
    volumes:
      - ~/docker_containers/jellyfin/config:/config
      - ~/docker_containers/jellyfin/cache:/cache
      - ~/Torrents:/media:ro
      - /home/unencrypted_torrents:/unencrypted_media:ro
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    #Notes: May need to line 
    #"Jellyfin.Networking.Manager.NetworkManager": "Warning"
    #to logging.json under "Serilogs": { "MinimumLevel": { "Default": "Information", "Override": {
    #to avoid spamming log file (docker compose logs -f)

  torrent:
    image: markusmcnugen/qbittorrentvpn
    container_name: qbittorrentvpn
    privileged: true
    environment:
      - TZ=America/Los_Angeles
      - PUID=998
      - PGID=100
      - WEBUI_PORT_ENV=8080
      - INCOMING_PORT_ENV=8999
      - VPN_ENABLED=yes
      - LAN_NETWORK=10.0.0.0/24
      - NAME_SERVERS=8.8.8.8,8.8.4.4
    volumes:
      - ~/docker_containers/qbittorent/config:/config #place vpn credentials in "config/openvpn/FILE_NAME.ovpn" under 'auth-user-pass'
      - ~/Torrents:/downloads
      - /home/unencrypted_torrents:/unencrypted_downloads #home dir encryption leads to 143 byte name limit vs 255 byte
    ports:
      - 8080:8080
      - 8999:8999
      - 8999:8999/udp
    restart: unless-stopped
